### ISSUE TITLE
Skrypty nie są w pełni kompatybilne z wersją Nintendo Switch

### ISSUE THREAD

**Issue by masagrator** [synspawacza/nier_automata_localization#8]
Tak jak w tytule.

Czy jest możliwość dodania wsparcia dla wersji Nintendo Switch?

Jakich plików to dotyczy:
- fonty (z tego co widzę skrypt polega na tym, że tekstury mają nagłówek DDS - w wersji na Switcha tych nagłówków nie ma, więc skrypty wywalają błąd o braku możliwości rozpoznania tekstury)
```
Extracting fonts from ftb files
Traceback (most recent call last):
  File "/mnt/d/NieR/nier_automata_localization-master/./tools/unpack_font.py", line 59, in <module>
    textures.append(Image.open(img_file))
  File "/usr/local/lib/python3.10/dist-packages/PIL/Image.py", line 3147, in open
    raise UnidentifiedImageError(
PIL.UnidentifiedImageError: cannot identify image file 'unpacked/font/font_00.dtt/font_00.wtp_000.dds'
```
- UI (ten sam problem co z fontami)
```
Extracting font 02 from unpacked/ui/ui_core_us.dat/messcore.mcd
Traceback (most recent call last):
  File "/mnt/d/NieR/nier_automata_localization-master/./tools/unpack_font.py", line 59, in <module>
    textures.append(Image.open(img_file))
  File "/usr/local/lib/python3.10/dist-packages/PIL/Image.py", line 3147, in open
    raise UnidentifiedImageError(
PIL.UnidentifiedImageError: cannot identify image file 'unpacked/ui/ui_core_us.dtt/messcore.wtp_000.dds'
```
- corehap.dat (wywala błąd dekodowania, więc zgaduję, że offsety są zmienione)
```
Extracting core/corehap.dat/core_hap.pak
Traceback (most recent call last):
  File "/mnt/d/NieR/nier_automata_localization-master/./tools/get_strings.py", line 61, in <module>
    extract_strings_to_file(args.input, args.output, args.lang, args.keep_non_ascii)
  File "/mnt/d/NieR/nier_automata_localization-master/./tools/get_strings.py", line 41, in extract_strings_to_file
    properties.serialize_properties(parsed.get_strings(lang), keep_non_ascii)
  File "/mnt/d/NieR/nier_automata_localization-master/tools/format/pak.py", line 89, in get_strings
    return charnames.File.parse(BytesIO(self.segments[25].unzip())).get_strings(
  File "/mnt/d/NieR/nier_automata_localization-master/tools/format/charnames.py", line 27, in parse
    result.entries[id] += read_zero_terminated_utf8(reader)
  File "/mnt/d/NieR/nier_automata_localization-master/tools/format/utils.py", line 72, in read_zero_terminated_utf8
    return read_utf8(reader, byte_count)
  File "/mnt/d/NieR/nier_automata_localization-master/tools/format/utils.py", line 63, in read_utf8
    return reader.read(byte_count).decode("utf-8").rstrip("\0")
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x83 in position 0: invalid start byte
```

Czy jest możliwość dodania wsparcia dla tych plików?
Próbowałem ogarnąć w jakim formacie są tekstury, bo wyglądają jak któryś DXT z alpha w hex edytorze, ale dostawałem tylko śmieci.

Link do paczki z plikami:
https://drive.google.com/file/d/1MRWv0EYIOHyagvDr9SGaI5dUNZ58YXVm/view?usp=sharing

**Comment by masagrator** [comment]
Tutaj na podstawie tego co ogarnęli na NieR Modding Discord opracowałem paczkę zdolną przekonertować tekstury fontów na png

[extract.zip](https://github.com/synspawacza/nier_automata_localization/files/9792402/extract.zip)

Do folderu ze skryptami wklej wta i wtp i użyj komendy z nazwą pliku bez typu
np.
```
python extract.py font_00
```

Wymagany jest `asct_decomp` zainstalowany przez pip

**Comment by synspawacza** [comment]
Dzięki za info.

Jeśli chodzi o `corehap.dat/core_hap.pak`, to faktycznie zmieniły się indeksy i wrzuciłem już poprawkę.

Spróbuję ogarnąć jak wrzucić konwersję ASTC na standardowego DDS, choć raczej wepnę się w `unpack_dds.py`

**Comment by masagrator** [comment]
Tutaj zrobiłem kompletną paczkę, która jest w stanie przekonwertować font z PC na Switcha. Może ci w czymś pomoże. :P
[font_converter.zip](https://github.com/synspawacza/nier_automata_localization/files/9797719/font_converter.zip)

**Comment by masagrator** [comment]
> Dzięki za info.
> 
> Jeśli chodzi o `corehap.dat/core_hap.pak`, to faktycznie zmieniły się indeksy i wrzuciłem już poprawkę.
> 
> Spróbuję ogarnąć jak wrzucić konwersję ASTC na standardowego DDS, choć raczej wepnę się w `unpack_dds.py`

Nadal nie wyciąga tekstów z globali w corehap

**Comment by synspawacza** [comment]
Dopiero teraz w weekend byłem w stanie spojrzeć na skrypty. W sumie to w pythonie wystarczy zrobić tylko swizzeling/deswizzeling, a kompresję/dekompresję już z oficjalnego enkodera. Poza tym zmieniły się długości rekordów w plikach wta (20 bajtów w wersji PC, 256 w Switchowej), muszę dostosować kod by działały obie wersje. Jak będę miał coś działającego to wrzucę do repo.

Co do tesktów w corehap to dziwne, bo u mnie działa na plikach które przesłałeś. Jakie masz md5 plików?
```
$ md5sum data/core/corehap.dat
2e08f4e46efed2095e41c35277bd2d1c  data/core/corehap.dat
$ md5sum unpacked/core/corehap.dat/core_hap.pak
e39c8b154fde800269768238a10354ae  unpacked/core/corehap.dat/core_hap.pak
$ ./tools/get_strings.py --lang en unpacked/core/corehap.dat/core_hap.pak source/core_hap.properties
$ head -n 4 source/core_hap.properties
a2=A2
a2b=2B
a9s=9S
rbot9s=Strange Machine Lifeform
```

**Comment by masagrator** [comment]
Znaczy się z core_hap.pak wypakowuje teksty, ale nie z globali, które są w corehap.dat

**Comment by synspawacza** [comment]
Dodałem obsługę budowania tekstur dla wersji switchowej, ale za bardzo nie mam jak sprawdzić czy pliki wynikowe działają ¯\\\_(ツ)_/¯

Niemniej, \*powinno\* działać

**Comment by masagrator** [comment]
globale działają, na próbę przepakowałem ui_core i font jest poharatany. 
Poprawnie wypakowuje glify z folderu font jakby co, więc problem najwyraźniej jest z konwersją z powrotem. Polecam użyć 4x4 jeśli tego nie zrobiłeś, bo wtedy działa to na tej samej zasadzie co swizzlowanie DXT5 co jest potwierdzone, że działa poprawnie. 

![2022102914191200](https://user-images.githubusercontent.com/8557858/198831025-ab5a2e2a-ec79-49da-8873-fd83409a83dc.jpg)

Jeszcze dodam informację, że gra zawiesza się w wersji na Switcha (przestaje reagować, nie crashuje się), jeśli napisy do prerenderowanych scen są umieszczone poza cpk (np. subtitles1400_us.dat. Jest używany w wideo, które się wyświetla, gdy jesteś AFK w menu tytułowym przed wejściem do głównego menu) i gra ma zamiar to wideo odtworzyć. Trzeba przepakować cpk dla tych napisów. Warto by było taką informację podać. Można spatchować z pomocą CriPakGui, sprawdzałem i działa bez problemu. A skoro już przepakowujemy data009.cpk, to można by również spatchować tam inne pliki, by zmniejszyć końcową wagę fanowskiego tłumaczenia.
https://github.com/CaptainSwag101/CriPakTools/releases
Nie wiem jakie inne napisy są do tego wykorzystywane.

**Comment by synspawacza** [comment]
Hmm, tekstury się wyświetlają, ale poszatkowane. IMO dalej jest problem z swizzlowaniem, ale za bardzo nie mam jak tego sprawdzić.

Z moich testów wynika, że swizzling 6x6 działa tak, że początek jest jak oryginał, ale wynikowa tekstura jest krótsza (z 360 448 bajtów robi się 237 568). Nie wiem jak gra to zareaguje, może zadziała, może będzie wymagać paddingu, może trzeba będzie poprawić algorytm swizzlowania.

Na osobnym [branchu](https://github.com/synspawacza/nier_automata_localization/tree/astc_test) zrobiłem skrypt `swizzle_test_build.sh`. Przepakowuje tylko teksture z `ui_title_us`, efekt powinien być widoczny w menu głównym. Może tak uda się dojść do tego, jak konwertować tekstury by działały na Switchu.

Proponuję spróbować z takimi parametrami (ewentualnie pobawić się BLOCK_SIZE i FORMAT_ID) i zobaczyć jak działają `output/ui/ui_title_us.dat` i `output/ui/ui_title_us.dtt`.
```
#Case 1 - swizzlowanie korzystając z oryginalnego ASTC (powstaje krótszy plik)
USE_OG_ASTC=1
BLOCK_SIZE=6
FORMAT_ID=0x7d
PADDING=0

#Case 2 - jak case 1, ale sztucznie dopycham zswizzlowaną teksturę zerami do oryginalnego rozmiaru
USE_OG_ASTC=1
BLOCK_SIZE=6
FORMAT_ID=0x7d
PADDING=360448

#Case 3 - jak case 1, ale korzystając z ASTC skonwertowanego z DDS
USE_OG_ASTC=0
BLOCK_SIZE=6
FORMAT_ID=0x7d
PADDING=0

#Case 4 - case 1 + case 3
USE_OG_ASTC=0
BLOCK_SIZE=6
FORMAT_ID=0x7d
PADDING=360448

#ASTC 4x4 skonwertowany z DDS
USE_OG_ASTC=0
BLOCK_SIZE=4
FORMAT_ID=0x79
PADDING=0
```

**Comment by masagrator** [comment]
Nie może być właśnie 6x6, bo wtedy astcenc stosuje jakąś dodatkową kompresję, która powoduje, że poprawne swizzlowanie jest niemożliwe. Dlatego jest różnica w rozmiarach. 
Przy 4x4 takich cudów nie uświadczyłem.

**Comment by masagrator** [comment]
Podsyłam mój link do swizzlera, który działa poprawnie z prawie wszystkimi teksturami ASTC 4x4, jakie testowałem

https://github.com/masagrator/NXGameScripts/tree/main/NieR%20Automata/astcSwizzler

Jedynie z jakiegoś powodu ui_debug nie jest odczytywany poprawnie, mimo że inne tekstury 256x256 jak w dlc2 i dlc3 działają poprawnie

**Comment by synspawacza** [comment]
> Podsyłam mój link do swizzlera, który działa poprawnie z prawie wszystkimi teksturami ASTC 4x4, jakie testowałem

Pliki wtp wygenerowane przez mój skrypt jest identyczny jak astc z twojego, co sugeruje że swizzluję poprawnie. Nie do końca rozumiem, co działa, a co nie; i jest do zrobienia.
